name: arrayseis
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3
    - pip
    - numpy=1.26.4
    - obspy
    - pygmt
    - numba
    - pyproj
    - pip:
      - git+https://github.com/caquigley/lts_array.git
      - pyyaml